version: '3'
services:
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - "${MONGO_BACKUP_DIR}:/data/db"

  mongoToEsTransporter:
    image: tombenke/mongo-to-es-transporter:latest
    environment:
      DB_NAME: "${DB_NAME}"
      MONGODB_URI: "${MONGODB_URI}"
      ELASTICSEARCH_URI: "${ELASTICSEARCH_URI}"
    links:
      - "mongo"
      - "elasticsearch"

  kibana:
    image: "kibana:latest"
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"

  elasticsearch:
    image: elasticsearch
    links:
      - "mongo"
    expose:
      - 9200
    ports:
      - "9200:9200"

